// AXELUS-WAF — Compliance Control Library
// Complete control sets for 10 major security standards.
// Each control maps to specific AXELUS-WAF modules and features.
// Publisher: OPTIMIUM NEXUS LLC — https://www.optimiumnexus.com
package engine

// loadAllControls populates the library with all standards' controls
func (l *ControlLibrary) loadAllControls() {
	l.loadPCIDSS()
	l.loadISO27001()
	l.loadSOC2()
	l.loadNISTCSF()
	l.loadGDPR()
	l.loadHIPAA()
	l.loadCISv8()
	l.loadNIS2()
	l.loadOWASP()
	l.loadFedRAMP()
}

// ── PCI DSS v4.0 ──────────────────────────────────────────────────────────────
// 12 Requirements, 300+ sub-controls. We map the WAF-relevant ones.
func (l *ControlLibrary) loadPCIDSS() {
	controls := []Control{
		// Requirement 1 — Network Security Controls
		{ID:"PCI-1.2.1", StandardID:StdPCIDSS, Section:"Req 1", Category:"Network Security",
			Title:"Network security controls are configured and maintained",
			Description:"All inbound and outbound traffic to and from the CDE is restricted to that which is necessary.",
			Guidance:"Configure AXELUS-WAF GeoIP rules and network ACLs to allow only necessary traffic.",
			Severity:SevHigh, Automated:true, WAFFeature:"geoip",
			WAFConfig:"GeoIP blocking rules active, default-deny posture",
			TestMethod:"Verify GeoIP rules count > 0 and default action is block/challenge",
			CrossRefs:[]string{"ISO-A.8.20","NIST-PR.AC-5","CIS-13.4"}},
		{ID:"PCI-1.3.1", StandardID:StdPCIDSS, Section:"Req 1", Category:"Network Security",
			Title:"Inbound traffic to the CDE is restricted",
			Description:"Inbound traffic is restricted to only that which is necessary and all other traffic is denied.",
			Guidance:"Use AXELUS-WAF with default-deny and explicit allowlist for CDE-bound traffic.",
			Severity:SevCritical, Automated:true, WAFFeature:"geoip",
			WAFConfig:"Default action: block. Allowlist only necessary source IPs/countries.",
			CrossRefs:[]string{"ISO-A.8.20","NIST-PR.AC-5"}},
		{ID:"PCI-1.4.1", StandardID:StdPCIDSS, Section:"Req 1", Category:"Network Security",
			Title:"NSCs are installed between trusted and untrusted networks",
			Description:"Network security controls exist between all wireless networks and the CDE.",
			Guidance:"Deploy AXELUS-WAF as the perimeter control between internet and CDE.",
			Severity:SevCritical, Automated:true, WAFFeature:"network_segmentation",
			WAFConfig:"Tengine reverse proxy deployed in front of all CDE services",
			CrossRefs:[]string{"ISO-A.8.20","CIS-13.1"}},

		// Requirement 2 — Secure Configurations
		{ID:"PCI-2.2.1", StandardID:StdPCIDSS, Section:"Req 2", Category:"Secure Configuration",
			Title:"Configuration standards are developed and implemented",
			Description:"Configuration standards address all system components and vendor default settings are changed.",
			Guidance:"AXELUS-WAF deploys with hardened defaults; admin password must be changed on first boot.",
			Severity:SevHigh, Automated:true, WAFFeature:"authentication",
			WAFConfig:"Default password changed, JWT secret rotated, all default keys replaced",
			CrossRefs:[]string{"ISO-A.8.9","CIS-4.1","NIST-PR.IP-1"}},
		{ID:"PCI-2.2.7", StandardID:StdPCIDSS, Section:"Req 2", Category:"Secure Configuration",
			Title:"All non-console administrative access is encrypted",
			Description:"All non-console administrative access uses strong cryptography.",
			Guidance:"AXELUS management API runs on TLS 1.3 only. All admin sessions use JWT over HTTPS.",
			Severity:SevCritical, Automated:true, WAFFeature:"encryption",
			WAFConfig:"TLS 1.3 enforced, HTTP redirected to HTTPS, cipher suite hardened",
			CrossRefs:[]string{"ISO-A.8.24","NIST-PR.DS-2","HIPAA-164.312(e)(2)(ii)"}},

		// Requirement 3 — Protect Stored Account Data
		{ID:"PCI-3.5.1", StandardID:StdPCIDSS, Section:"Req 3", Category:"Data Protection",
			Title:"Primary Account Numbers (PAN) are secured with strong cryptography",
			Description:"PAN is secured with strong cryptography wherever stored.",
			Guidance:"AXELUS-WAF does not store PAN data. Verify no card data passes through WAF logs unmasked.",
			Severity:SevCritical, Automated:false, WAFFeature:"data_protection",
			WAFConfig:"Log masking enabled for patterns matching PAN format (\\d{4}[-\\s]\\d{4}[-\\s]\\d{4}[-\\s]\\d{4})",
			CrossRefs:[]string{"ISO-A.8.24","GDPR-Art.32"}},

		// Requirement 4 — Protect Cardholder Data Transmissions
		{ID:"PCI-4.2.1", StandardID:StdPCIDSS, Section:"Req 4", Category:"Encryption in Transit",
			Title:"Strong cryptography is used for all transmissions of PAN over open networks",
			Description:"Only trusted keys and certificates are accepted. TLS 1.2+ required, TLS 1.3 preferred.",
			Guidance:"AXELUS-WAF enforces TLS 1.3 with strong cipher suites on all listener ports.",
			Severity:SevCritical, Automated:true, WAFFeature:"encryption",
			WAFConfig:"TLS 1.3 (preferred), min TLS 1.2, ciphers: TLS_AES_256_GCM_SHA384",
			CrossRefs:[]string{"ISO-A.8.24","NIST-PR.DS-2","HIPAA-164.312(e)(1)"}},

		// Requirement 5 — Malware Protection
		{ID:"PCI-5.2.1", StandardID:StdPCIDSS, Section:"Req 5", Category:"Malware Protection",
			Title:"Anti-malware solution is deployed on all system components",
			Description:"An anti-malware solution is deployed and activated on all system components.",
			Guidance:"AXELUS-WAF's ML pipeline detects malicious payloads. Complement with host-based AV.",
			Severity:SevHigh, Automated:true, WAFFeature:"vulnerability_scan",
			WAFConfig:"ML Zero-Day Shield active, OWASP rules enabled, heuristic fallback active",
			CrossRefs:[]string{"ISO-A.8.7","CIS-10.1","NIST-DE.CM-4"}},

		// Requirement 6 — Secure Systems and Software
		{ID:"PCI-6.2.4", StandardID:StdPCIDSS, Section:"Req 6", Category:"Secure Development",
			Title:"Software development practices prevent introduction of vulnerabilities",
			Description:"Training on secure coding, security testing is part of SDLC.",
			Guidance:"AXELUS CI/CD includes Trivy security scanning and automated SAST.",
			Severity:SevHigh, Automated:true, WAFFeature:"patch_management",
			WAFConfig:"GitHub Actions CI with Trivy container scan, go vet, golangci-lint",
			CrossRefs:[]string{"ISO-A.8.25","NIST-PR.IP-2","CIS-16.14"}},
		{ID:"PCI-6.4.1", StandardID:StdPCIDSS, Section:"Req 6", Category:"Web Application Security",
			Title:"Public-facing web applications are protected against attacks",
			Description:"A WAF is deployed in front of public-facing web applications.",
			Guidance:"AXELUS-WAF IS this control. Verify WAF is active and blocking attacks.",
			Severity:SevCritical, Automated:true, WAFFeature:"vulnerability_scan",
			WAFConfig:"AXELUS-WAF active, OWASP Top 10 rules enabled, ML detection enabled",
			TestMethod:"Verify attacks_blocked_24h > 0 AND ml_model_active = true",
			CrossRefs:[]string{"ISO-A.8.8","NIST-DE.CM-4","OWASP-A06"}},
		{ID:"PCI-6.4.2", StandardID:StdPCIDSS, Section:"Req 6", Category:"Web Application Security",
			Title:"WAF is actively running and up to date",
			Description:"WAF is in active blocking mode, not detection-only, and rules are current.",
			Guidance:"AXELUS-WAF must be in blocking mode with daily rule updates.",
			Severity:SevCritical, Automated:true, WAFFeature:"vulnerability_scan",
			WAFConfig:"Mode: block (not monitor-only), rule update: automated via CI/CD",
			CrossRefs:[]string{"ISO-A.8.8","OWASP-A06"}},

		// Requirement 7 — Restrict Access
		{ID:"PCI-7.2.1", StandardID:StdPCIDSS, Section:"Req 7", Category:"Access Control",
			Title:"Access controls define what access is allowed to system components",
			Description:"Access control systems are in place to enforce least privilege.",
			Guidance:"AXELUS RBAC system enforces least privilege with 8 roles and 14 permissions.",
			Severity:SevHigh, Automated:true, WAFFeature:"access_control",
			WAFConfig:"RBAC: super_admin/admin/support/operator/viewer, principle of least privilege",
			CrossRefs:[]string{"ISO-A.8.3","NIST-PR.AC-3","CIS-6.1"}},

		// Requirement 8 — Identify and Authenticate Users
		{ID:"PCI-8.3.6", StandardID:StdPCIDSS, Section:"Req 8", Category:"Authentication",
			Title:"Passwords/passphrases have minimum length of 12 characters",
			Description:"All user and system passwords meet minimum complexity requirements.",
			Guidance:"AXELUS enforces minimum 10-char passwords (bcrypt cost=12) for admin accounts.",
			Severity:SevHigh, Automated:true, WAFFeature:"authentication",
			WAFConfig:"bcrypt cost=12, min length=10 chars enforced in user creation API",
			CrossRefs:[]string{"ISO-A.8.5","NIST-PR.AC-1","CIS-5.2"}},
		{ID:"PCI-8.4.2", StandardID:StdPCIDSS, Section:"Req 8", Category:"MFA",
			Title:"MFA is implemented for all access into the CDE",
			Description:"Multi-factor authentication is required for all CDE access.",
			Guidance:"AXELUS admin portal supports TOTP MFA. Enable mandatory MFA enforcement.",
			Severity:SevCritical, Automated:true, WAFFeature:"authentication",
			WAFConfig:"MFA: TOTP (RFC 6238) available. Set mfa_required=true for CDE admin role",
			CrossRefs:[]string{"ISO-A.8.5","NIST-PR.AC-7","CIS-6.3"}},

		// Requirement 10 — Log and Monitor
		{ID:"PCI-10.2.1", StandardID:StdPCIDSS, Section:"Req 10", Category:"Logging",
			Title:"Audit logs capture all individual user access to cardholder data",
			Description:"Log entries include user identification, type of event, date/time, success/failure.",
			Guidance:"AXELUS audit log captures all actions with user ID, timestamp, IP, action, status.",
			Severity:SevCritical, Automated:true, WAFFeature:"logging",
			WAFConfig:"AuditLog table: all admin actions logged with user_id, ip, user_agent, occurred_at",
			CrossRefs:[]string{"ISO-A.8.15","NIST-DE.CM-3","SOC2-CC7.2"}},
		{ID:"PCI-10.5.1", StandardID:StdPCIDSS, Section:"Req 10", Category:"Log Integrity",
			Title:"Retain audit log history for at least 12 months",
			Description:"Audit logs are retained for at least 12 months; 3 months immediately available.",
			Guidance:"AXELUS Kafka topic axelus.audit.log with 12-month retention. PostgreSQL audit table.",
			Severity:SevHigh, Automated:true, WAFFeature:"logging",
			WAFConfig:"Kafka retention: 365 days. PostgreSQL: audit_logs table, no auto-delete",
			CrossRefs:[]string{"ISO-A.8.15","NIST-PR.PT-1","HIPAA-164.312(b)"}},
		{ID:"PCI-10.7.1", StandardID:StdPCIDSS, Section:"Req 10", Category:"Monitoring",
			Title:"Failures of critical security controls are detected and reported",
			Description:"Failures of critical security controls are detected, alerted and addressed promptly.",
			Guidance:"AXELUS Prometheus + AlertManager with PagerDuty/Slack/Teams integration.",
			Severity:SevHigh, Automated:true, WAFFeature:"monitoring",
			WAFConfig:"AlertManager: rules for WAF down, high block rate, cert expiry, model drift",
			CrossRefs:[]string{"ISO-A.8.16","NIST-DE.AE-4","CIS-13.9"}},

		// Requirement 11 — Test Security
		{ID:"PCI-11.3.1", StandardID:StdPCIDSS, Section:"Req 11", Category:"Penetration Testing",
			Title:"Internal penetration testing is performed at least annually",
			Description:"Penetration testing is performed per a defined methodology.",
			Guidance:"AXELUS-WAF honeypot layer captures attacker techniques for pen test evidence.",
			Severity:SevHigh, Automated:false, WAFFeature:"vulnerability_scan",
			WAFConfig:"Honeypot: 25 trap paths. PCAP forensics captures attack patterns.",
			CrossRefs:[]string{"ISO-A.8.8","NIST-DE.DP-3"}},
		{ID:"PCI-11.5.1", StandardID:StdPCIDSS, Section:"Req 11", Category:"Intrusion Detection",
			Title:"Intrusion-detection and/or intrusion-prevention techniques detect attacks",
			Description:"IDS/IPS is deployed to detect and/or prevent intrusions.",
			Guidance:"AXELUS-WAF IS the IDS/IPS. ML Zero-Day Shield + DPI + behavioral analytics.",
			Severity:SevCritical, Automated:true, WAFFeature:"monitoring",
			WAFConfig:"ML Zero-Day Shield + DPI + UBA + DDoS detection all active",
			CrossRefs:[]string{"ISO-A.8.16","NIST-DE.CM-4","CIS-13.7"}},

		// Requirement 12 — Support Information Security
		{ID:"PCI-12.10.1", StandardID:StdPCIDSS, Section:"Req 12", Category:"Incident Response",
			Title:"Incident response plan exists and is ready to be activated",
			Description:"An incident response plan that can be activated in the event of a breach.",
			Guidance:"AXELUS automated IR: BGP null-routing + alert notifications + forensics capture.",
			Severity:SevHigh, Automated:true, WAFFeature:"incident_response",
			WAFConfig:"Auto-IR: DDoS → BGP null-route, Attack → PagerDuty + PCAP capture",
			CrossRefs:[]string{"ISO-A.5.26","NIST-RS.RP-1","CIS-17.1"}},
	}
	for _, c := range controls { l.Register(c) }
}

// ── ISO/IEC 27001:2022 ────────────────────────────────────────────────────────
func (l *ControlLibrary) loadISO27001() {
	controls := []Control{
		{ID:"ISO-A.5.7", StandardID:StdISO27001, Section:"A.5 Organizational", Category:"Threat Intelligence",
			Title:"Threat intelligence",
			Description:"Information relating to information security threats is collected and analysed.",
			Guidance:"AXELUS Threat Intelligence module aggregates feeds from AbuseIPDB, custom feeds, and cross-tenant correlation.",
			Severity:SevHigh, Automated:true, WAFFeature:"monitoring",
			WAFConfig:"Threat Intel: AbuseIPDB API + custom STIX/TAXII feeds enabled",
			CrossRefs:[]string{"PCI-11.5.1","NIST-DE.CM-4","NIS2-Art.21"}},
		{ID:"ISO-A.5.23", StandardID:StdISO27001, Section:"A.5 Organizational", Category:"Cloud Security",
			Title:"Information security for use of cloud services",
			Description:"Processes for acquisition, use, management, and exit from cloud services.",
			Guidance:"AXELUS Kubernetes Helm chart with network policies, RBAC, and pod security standards.",
			Severity:SevMedium, Automated:true, WAFFeature:"network_segmentation",
			WAFConfig:"K8s: 9 NetworkPolicies, PodDisruptionBudget, HorizontalPodAutoscaler",
			CrossRefs:[]string{"NIST-PR.AC-5","CIS-13.1"}},
		{ID:"ISO-A.5.26", StandardID:StdISO27001, Section:"A.5 Organizational", Category:"Incident Response",
			Title:"Response to information security incidents",
			Description:"Incidents are responded to in accordance with the documented procedures.",
			Guidance:"AXELUS automated incident response: BGP null-routing, alerting, forensics.",
			Severity:SevHigh, Automated:true, WAFFeature:"incident_response",
			CrossRefs:[]string{"PCI-12.10.1","NIST-RS.RP-1","NIS2-Art.21"}},
		{ID:"ISO-A.5.29", StandardID:StdISO27001, Section:"A.5 Organizational", Category:"Business Continuity",
			Title:"Information security during disruption",
			Description:"Maintain information security at appropriate levels during disruption.",
			Guidance:"AXELUS: Kubernetes HPA for auto-scaling, BGP null-routing for DDoS, Redis HA.",
			Severity:SevHigh, Automated:true, WAFFeature:"network_segmentation",
			CrossRefs:[]string{"NIST-RC.RP-1","CIS-11.3"}},
		{ID:"ISO-A.8.3", StandardID:StdISO27001, Section:"A.8 Technological", Category:"Access Control",
			Title:"Information access restriction",
			Description:"Access to information and other assets is restricted in accordance with the access control policy.",
			Guidance:"AXELUS RBAC with tenant isolation. Each tenant sees only their own data (data prefix isolation).",
			Severity:SevHigh, Automated:true, WAFFeature:"access_control",
			CrossRefs:[]string{"PCI-7.2.1","NIST-PR.AC-3","CIS-6.1","GDPR-Art.32"}},
		{ID:"ISO-A.8.5", StandardID:StdISO27001, Section:"A.8 Technological", Category:"Authentication",
			Title:"Secure authentication",
			Description:"Secure authentication technologies and procedures are implemented based on information access restrictions.",
			Guidance:"AXELUS: JWT (HS256), bcrypt (cost=12), TOTP MFA, API key rotation.",
			Severity:SevCritical, Automated:true, WAFFeature:"authentication",
			CrossRefs:[]string{"PCI-8.3.6","PCI-8.4.2","NIST-PR.AC-7","HIPAA-164.312(d)"}},
		{ID:"ISO-A.8.7", StandardID:StdISO27001, Section:"A.8 Technological", Category:"Malware Protection",
			Title:"Protection against malware",
			Description:"Protection against malware is implemented and supported by appropriate user awareness.",
			Guidance:"AXELUS ML pipeline (ONNX) + OWASP rules + Zero-Day Shield.",
			Severity:SevHigh, Automated:true, WAFFeature:"vulnerability_scan",
			CrossRefs:[]string{"PCI-5.2.1","CIS-10.1","NIST-DE.CM-4"}},
		{ID:"ISO-A.8.8", StandardID:StdISO27001, Section:"A.8 Technological", Category:"Vulnerability Management",
			Title:"Management of technical vulnerabilities",
			Description:"Information about technical vulnerabilities is obtained, the organisation's exposure to such vulnerabilities is evaluated.",
			Guidance:"AXELUS CI/CD with Trivy scanning. WAF rules updated automatically via deployment pipeline.",
			Severity:SevHigh, Automated:true, WAFFeature:"patch_management",
			CrossRefs:[]string{"PCI-6.2.4","PCI-6.4.1","NIST-DE.CM-8","CIS-7.4"}},
		{ID:"ISO-A.8.9", StandardID:StdISO27001, Section:"A.8 Technological", Category:"Configuration Management",
			Title:"Configuration management",
			Description:"Configurations, including security configurations, of hardware, software, services and networks are established, documented, implemented, monitored and reviewed.",
			Guidance:"AXELUS: all config as Kubernetes YAML, Helm values, Docker Compose. GitOps workflow.",
			Severity:SevMedium, Automated:true, WAFFeature:"patch_management",
			CrossRefs:[]string{"PCI-2.2.1","CIS-4.1","NIST-PR.IP-1"}},
		{ID:"ISO-A.8.15", StandardID:StdISO27001, Section:"A.8 Technological", Category:"Logging",
			Title:"Logging",
			Description:"Logs that record activities, exceptions, faults and other relevant events are produced, stored, protected and analysed.",
			Guidance:"AXELUS: immutable audit log in PostgreSQL + Kafka stream + SIEM forwarding.",
			Severity:SevHigh, Automated:true, WAFFeature:"logging",
			CrossRefs:[]string{"PCI-10.2.1","PCI-10.5.1","NIST-PR.PT-1","SOC2-CC7.2"}},
		{ID:"ISO-A.8.16", StandardID:StdISO27001, Section:"A.8 Technological", Category:"Monitoring",
			Title:"Monitoring activities",
			Description:"Networks, systems and applications are monitored for anomalous behaviour and appropriate actions are taken to evaluate potential information security incidents.",
			Guidance:"AXELUS: Prometheus + Grafana (18 panels) + UBA/UEBA + real-time threat detection.",
			Severity:SevHigh, Automated:true, WAFFeature:"monitoring",
			CrossRefs:[]string{"PCI-10.7.1","PCI-11.5.1","NIST-DE.CM-3","NIS2-Art.21"}},
		{ID:"ISO-A.8.20", StandardID:StdISO27001, Section:"A.8 Technological", Category:"Network Security",
			Title:"Networks security",
			Description:"Networks and network devices are secured, managed and controlled to protect information in systems and applications.",
			Guidance:"AXELUS: GeoIP blocking, mTLS mesh, Kubernetes NetworkPolicies, BGP null-routing.",
			Severity:SevHigh, Automated:true, WAFFeature:"network_segmentation",
			CrossRefs:[]string{"PCI-1.2.1","PCI-1.3.1","NIST-PR.AC-5","CIS-13.4"}},
		{ID:"ISO-A.8.23", StandardID:StdISO27001, Section:"A.8 Technological", Category:"Web Filtering",
			Title:"Web filtering",
			Description:"Access to external websites is managed to reduce exposure to malicious content.",
			Guidance:"AXELUS deep packet inspection + honeypot + threat intelligence feeds.",
			Severity:SevMedium, Automated:true, WAFFeature:"vulnerability_scan",
			CrossRefs:[]string{"CIS-9.2","NIST-PR.DS-6"}},
		{ID:"ISO-A.8.24", StandardID:StdISO27001, Section:"A.8 Technological", Category:"Cryptography",
			Title:"Use of cryptography",
			Description:"Rules for the effective use of cryptography, including cryptographic key management.",
			Guidance:"AXELUS: TLS 1.3, ED25519 license signing, bcrypt auth, AES-256-GCM storage.",
			Severity:SevCritical, Automated:true, WAFFeature:"encryption",
			CrossRefs:[]string{"PCI-4.2.1","NIST-PR.DS-2","HIPAA-164.312(e)(2)(ii)"}},
		{ID:"ISO-A.8.25", StandardID:StdISO27001, Section:"A.8 Technological", Category:"Secure Development",
			Title:"Secure development life cycle",
			Description:"Rules for the secure development of software and systems are established and applied.",
			Guidance:"AXELUS: Trivy scanning in CI, golangci-lint, SAST, dependency audit.",
			Severity:SevHigh, Automated:true, WAFFeature:"patch_management",
			CrossRefs:[]string{"PCI-6.2.4","NIST-PR.IP-2","CIS-16.14"}},
	}
	for _, c := range controls { l.Register(c) }
}

// ── SOC 2 Type II ─────────────────────────────────────────────────────────────
func (l *ControlLibrary) loadSOC2() {
	controls := []Control{
		{ID:"SOC2-CC1.1", StandardID:StdSOC2, Section:"CC1 Control Environment", Category:"Governance",
			Title:"COSO Principle 1: Demonstrates commitment to integrity and ethical values",
			Description:"Policies and procedures demonstrate the entity's commitment to competence, integrity.",
			Guidance:"AXELUS: documented security policies, code of conduct, OPTIMIUM NEXUS LLC governance.",
			Severity:SevLow, Automated:false, WAFFeature:"access_control",
			CrossRefs:[]string{"ISO-A.5.1","NIST-GV.OC-1"}},
		{ID:"SOC2-CC2.1", StandardID:StdSOC2, Section:"CC2 Communication", Category:"Communication",
			Title:"Communication of internal control information",
			Description:"Internal communications include adequate information about objectives and responsibilities.",
			Guidance:"AXELUS Admin Center audit log available to all authorized stakeholders.",
			Severity:SevLow, Automated:true, WAFFeature:"logging",
			CrossRefs:[]string{"ISO-A.8.15","PCI-10.2.1"}},
		{ID:"SOC2-CC3.1", StandardID:StdSOC2, Section:"CC3 Risk Assessment", Category:"Risk Assessment",
			Title:"Entity specifies objectives with sufficient clarity",
			Description:"Operations and compliance objectives are specified with sufficient clarity.",
			Guidance:"Compliance reports from AXELUS engine provide risk scoring and gap analysis.",
			Severity:SevMedium, Automated:true, WAFFeature:"monitoring",
			CrossRefs:[]string{"ISO-A.5.7","NIST-GV.RM-1"}},
		{ID:"SOC2-CC5.2", StandardID:StdSOC2, Section:"CC5 Control Activities", Category:"Access Control",
			Title:"Control activities are selected for risk mitigation",
			Description:"The entity selects and develops control activities that mitigate risks.",
			Guidance:"AXELUS: RBAC, mTLS, GeoIP blocking, rate limiting, ML detection — all automated.",
			Severity:SevHigh, Automated:true, WAFFeature:"access_control",
			CrossRefs:[]string{"PCI-7.2.1","ISO-A.8.3","NIST-PR.AC-3"}},
		{ID:"SOC2-CC6.1", StandardID:StdSOC2, Section:"CC6 Logical Access", Category:"Logical Access",
			Title:"Logical access security software, infrastructure, and architectures",
			Description:"The entity implements logical access security measures to protect against unauthorized access.",
			Guidance:"AXELUS: JWT auth, bcrypt, API keys, TOTP MFA, session management.",
			Severity:SevCritical, Automated:true, WAFFeature:"authentication",
			CrossRefs:[]string{"PCI-8.3.6","ISO-A.8.5","NIST-PR.AC-7"}},
		{ID:"SOC2-CC6.6", StandardID:StdSOC2, Section:"CC6 Logical Access", Category:"Vulnerability Management",
			Title:"Security vulnerabilities are identified and evaluated",
			Description:"The entity identifies and evaluates security vulnerabilities that may threaten achievement of objectives.",
			Guidance:"AXELUS ML Zero-Day Shield + OWASP rules + automated Trivy scanning.",
			Severity:SevHigh, Automated:true, WAFFeature:"vulnerability_scan",
			CrossRefs:[]string{"PCI-11.3.1","ISO-A.8.8","NIST-DE.CM-8"}},
		{ID:"SOC2-CC7.1", StandardID:StdSOC2, Section:"CC7 System Operations", Category:"Change Detection",
			Title:"Environmental and configuration changes are monitored",
			Description:"The entity detects and monitors for new vulnerabilities and environmental threats.",
			Guidance:"AXELUS Compliance Monitor runs periodic assessments and detects drift (>5pt score drop).",
			Severity:SevHigh, Automated:true, WAFFeature:"monitoring",
			CrossRefs:[]string{"ISO-A.8.9","NIST-DE.CM-7"}},
		{ID:"SOC2-CC7.2", StandardID:StdSOC2, Section:"CC7 System Operations", Category:"Anomaly Detection",
			Title:"Anomalies and security incidents are identified",
			Description:"The entity monitors system components for anomalies that indicate malicious or unauthorized behavior.",
			Guidance:"AXELUS UBA/UEBA (8 behavioral signals), ML Zero-Day Shield, Kafka streaming.",
			Severity:SevCritical, Automated:true, WAFFeature:"monitoring",
			CrossRefs:[]string{"PCI-11.5.1","ISO-A.8.16","NIST-DE.AE-2"}},
		{ID:"SOC2-CC7.3", StandardID:StdSOC2, Section:"CC7 System Operations", Category:"Incident Response",
			Title:"Security incidents are responded to according to procedures",
			Description:"The entity evaluates security events to determine if they constitute security incidents.",
			Guidance:"AXELUS: automated IR pipeline — alert → forensics capture → BGP null-route → notify.",
			Severity:SevHigh, Automated:true, WAFFeature:"incident_response",
			CrossRefs:[]string{"PCI-12.10.1","ISO-A.5.26","NIST-RS.RP-1"}},
		{ID:"SOC2-CC8.1", StandardID:StdSOC2, Section:"CC8 Change Management", Category:"Change Management",
			Title:"Change management controls",
			Description:"Changes to infrastructure, data, software, and procedures are authorized, designed, and implemented.",
			Guidance:"AXELUS: GitOps workflow, Helm chart versioning, semantic version tags, CI gating.",
			Severity:SevMedium, Automated:true, WAFFeature:"patch_management",
			CrossRefs:[]string{"ISO-A.8.9","NIST-PR.IP-3","CIS-4.1"}},
		{ID:"SOC2-A1.1", StandardID:StdSOC2, Section:"Availability", Category:"Availability",
			Title:"Availability performance objectives are identified",
			Description:"Current processing capacity and availability performance objectives are identified.",
			Guidance:"AXELUS: Kubernetes HPA, PDB, Redis HA, multi-node Tengine, BGP null-routing for DDoS.",
			Severity:SevHigh, Automated:true, WAFFeature:"network_segmentation",
			CrossRefs:[]string{"ISO-A.5.29","NIST-RC.RP-1"}},
	}
	for _, c := range controls { l.Register(c) }
}

// ── NIST CSF 2.0 ──────────────────────────────────────────────────────────────
func (l *ControlLibrary) loadNISTCSF() {
	controls := []Control{
		{ID:"NIST-GV.OC-1", StandardID:StdNISTCSF, Section:"GOVERN", Category:"Governance",
			Title:"Cybersecurity risk strategy and policies are established",
			Description:"Organizational context, roles and responsibilities for cybersecurity risk management.",
			Guidance:"AXELUS: Multi-tenant admin center with RBAC, audit trail, and compliance reporting.",
			Severity:SevMedium, Automated:true, WAFFeature:"access_control",
			CrossRefs:[]string{"ISO-A.5.1","SOC2-CC1.1"}},
		{ID:"NIST-GV.RM-1", StandardID:StdNISTCSF, Section:"GOVERN", Category:"Risk Management",
			Title:"Risk management objectives are established and agreed to",
			Description:"Risk tolerance for the organization's risk management strategy is determined.",
			Guidance:"AXELUS Compliance Engine scores each control 0-100 and provides risk scoring.",
			Severity:SevMedium, Automated:true, WAFFeature:"monitoring",
			CrossRefs:[]string{"SOC2-CC3.1","ISO-A.5.7"}},
		{ID:"NIST-ID.AM-1", StandardID:StdNISTCSF, Section:"IDENTIFY", Category:"Asset Management",
			Title:"Inventories of hardware managed by the organization are maintained",
			Description:"Hardware assets that are owned or managed by the organization are inventoried.",
			Guidance:"AXELUS: Kubernetes resource inventory, tenant asset catalog in admin portal.",
			Severity:SevMedium, Automated:true, WAFFeature:"monitoring",
			CrossRefs:[]string{"CIS-1.1","ISO-A.5.9"}},
		{ID:"NIST-PR.AC-1", StandardID:StdNISTCSF, Section:"PROTECT", Category:"Access Control",
			Title:"Identities and credentials are issued, managed, and revoked",
			Description:"Identities and credentials for authorized devices, users and processes are managed.",
			Guidance:"AXELUS: JWT lifecycle management, API key rotation, user CRUD with audit.",
			Severity:SevHigh, Automated:true, WAFFeature:"authentication",
			CrossRefs:[]string{"PCI-8.3.6","ISO-A.8.5","CIS-5.1"}},
		{ID:"NIST-PR.AC-5", StandardID:StdNISTCSF, Section:"PROTECT", Category:"Network Segmentation",
			Title:"Network integrity is protected with network segmentation",
			Description:"Network integrity is protected, incorporating network segregation where appropriate.",
			Guidance:"AXELUS: GeoIP blocking, Kubernetes NetworkPolicies (9), mTLS SPIFFE mesh.",
			Severity:SevHigh, Automated:true, WAFFeature:"network_segmentation",
			CrossRefs:[]string{"PCI-1.2.1","ISO-A.8.20","CIS-13.4"}},
		{ID:"NIST-PR.AC-7", StandardID:StdNISTCSF, Section:"PROTECT", Category:"Authentication",
			Title:"Users, devices and other assets are authenticated with strength",
			Description:"Authentication commensurate with the risk of the transaction or interaction.",
			Guidance:"AXELUS: TOTP MFA, bcrypt (cost=12), JWT (8h expiry), API key auth.",
			Severity:SevCritical, Automated:true, WAFFeature:"authentication",
			CrossRefs:[]string{"PCI-8.4.2","ISO-A.8.5","CIS-6.3"}},
		{ID:"NIST-PR.DS-2", StandardID:StdNISTCSF, Section:"PROTECT", Category:"Data in Transit",
			Title:"Data-in-transit is protected",
			Description:"Data-in-transit is protected using cryptographic techniques.",
			Guidance:"AXELUS: TLS 1.3 enforced, no plaintext HTTP to backend, mTLS inter-service.",
			Severity:SevCritical, Automated:true, WAFFeature:"encryption",
			CrossRefs:[]string{"PCI-4.2.1","ISO-A.8.24","HIPAA-164.312(e)(1)"}},
		{ID:"NIST-PR.DS-6", StandardID:StdNISTCSF, Section:"PROTECT", Category:"Data Integrity",
			Title:"Integrity checking mechanisms are used to verify software and firmware",
			Description:"Software integrity is verified to detect unauthorized tampering.",
			Guidance:"AXELUS: Trivy container image signing, Git commit signing, Helm chart checksums.",
			Severity:SevHigh, Automated:true, WAFFeature:"patch_management",
			CrossRefs:[]string{"ISO-A.8.25","CIS-7.3"}},
		{ID:"NIST-PR.IP-1", StandardID:StdNISTCSF, Section:"PROTECT", Category:"Baselines",
			Title:"A baseline configuration is established and maintained",
			Description:"Baseline configuration of information technology/industrial control systems.",
			Guidance:"AXELUS: Helm values.yaml as baseline, GitOps enforcement, IaC in repo.",
			Severity:SevMedium, Automated:true, WAFFeature:"patch_management",
			CrossRefs:[]string{"PCI-2.2.1","ISO-A.8.9","CIS-4.1"}},
		{ID:"NIST-DE.AE-2", StandardID:StdNISTCSF, Section:"DETECT", Category:"Anomaly Detection",
			Title:"Potentially adverse events are analyzed to better understand attack methods",
			Description:"Anomalies that indicate adverse events are detected.",
			Guidance:"AXELUS: ML pipeline (64 features, 15 classes), UBA (8 behavioral signals), DPI.",
			Severity:SevHigh, Automated:true, WAFFeature:"monitoring",
			CrossRefs:[]string{"SOC2-CC7.2","ISO-A.8.16","PCI-11.5.1"}},
		{ID:"NIST-DE.CM-3", StandardID:StdNISTCSF, Section:"DETECT", Category:"Continuous Monitoring",
			Title:"Personnel activity and technology usage are monitored",
			Description:"Personnel activity and technology usage are monitored to find potential security events.",
			Guidance:"AXELUS: UBA/UEBA profiler tracks 25+ behavioral dimensions per entity.",
			Severity:SevHigh, Automated:true, WAFFeature:"monitoring",
			CrossRefs:[]string{"PCI-10.7.1","ISO-A.8.16","SOC2-CC7.1"}},
		{ID:"NIST-DE.CM-4", StandardID:StdNISTCSF, Section:"DETECT", Category:"Malware Detection",
			Title:"Malicious code is detected",
			Description:"Malicious code is detected to find potential security events.",
			Guidance:"AXELUS: ML Zero-Day Shield (Isolation Forest + ONNX), OWASP rules, DPI.",
			Severity:SevCritical, Automated:true, WAFFeature:"vulnerability_scan",
			CrossRefs:[]string{"PCI-5.2.1","PCI-6.4.1","ISO-A.8.7","CIS-10.1"}},
		{ID:"NIST-RS.RP-1", StandardID:StdNISTCSF, Section:"RESPOND", Category:"Incident Response",
			Title:"Incident response plan is executed during or after a cybersecurity incident",
			Description:"A response plan is executed during or after an incident.",
			Guidance:"AXELUS: auto-IR chain — detect → BGP null-route → PCAP capture → alert → notify.",
			Severity:SevHigh, Automated:true, WAFFeature:"incident_response",
			CrossRefs:[]string{"PCI-12.10.1","ISO-A.5.26","SOC2-CC7.3"}},
		{ID:"NIST-RC.RP-1", StandardID:StdNISTCSF, Section:"RECOVER", Category:"Recovery Planning",
			Title:"Execution of the recovery plan is started after an incident",
			Description:"Recovery plan is executed during or after a cybersecurity incident.",
			Guidance:"AXELUS: BGP route withdrawal restores traffic, Kubernetes self-healing pods.",
			Severity:SevMedium, Automated:true, WAFFeature:"incident_response",
			CrossRefs:[]string{"ISO-A.5.29","SOC2-A1.1","CIS-11.3"}},
	}
	for _, c := range controls { l.Register(c) }
}

// ── GDPR ──────────────────────────────────────────────────────────────────────
func (l *ControlLibrary) loadGDPR() {
	controls := []Control{
		{ID:"GDPR-Art.5", StandardID:StdGDPR, Section:"Chapter II — Principles", Category:"Data Principles",
			Title:"Principles relating to processing of personal data",
			Description:"Personal data must be processed lawfully, fairly, transparently, for a specified purpose, minimised, accurate, and kept securely.",
			Guidance:"AXELUS: PCAP capture mode can exclude body (header-only) to minimise PII. Retention policies enforced.",
			Severity:SevCritical, Automated:true, WAFFeature:"data_protection",
			CrossRefs:[]string{"ISO-A.8.24","PCI-3.5.1","HIPAA-164.514"}},
		{ID:"GDPR-Art.25", StandardID:StdGDPR, Section:"Chapter IV — Controller", Category:"Privacy by Design",
			Title:"Data protection by design and by default",
			Description:"Implement appropriate technical and organisational measures to implement data-protection principles effectively.",
			Guidance:"AXELUS: PII masking in logs, GDPR capture mode (headers-only), data minimisation in forensics.",
			Severity:SevHigh, Automated:true, WAFFeature:"data_protection",
			WAFConfig:"CaptureMode=header_only for GDPR tenants, PAN pattern masking in logs",
			CrossRefs:[]string{"ISO-A.8.24","NIST-PR.DS-2"}},
		{ID:"GDPR-Art.30", StandardID:StdGDPR, Section:"Chapter IV — Controller", Category:"Records of Processing",
			Title:"Records of processing activities",
			Description:"Each controller maintains a record of processing activities.",
			Guidance:"AXELUS audit log and Kafka stream provide immutable processing records.",
			Severity:SevHigh, Automated:true, WAFFeature:"logging",
			CrossRefs:[]string{"ISO-A.8.15","PCI-10.2.1"}},
		{ID:"GDPR-Art.32", StandardID:StdGDPR, Section:"Chapter IV — Security", Category:"Security of Processing",
			Title:"Security of processing",
			Description:"Implement appropriate technical measures to ensure security appropriate to the risk, including encryption, pseudonymisation, confidentiality, availability.",
			Guidance:"AXELUS: AES-256-GCM, TLS 1.3, bcrypt, mTLS, Kubernetes NetworkPolicies.",
			Severity:SevCritical, Automated:true, WAFFeature:"encryption",
			CrossRefs:[]string{"ISO-A.8.24","PCI-4.2.1","HIPAA-164.312(e)(1)"}},
		{ID:"GDPR-Art.33", StandardID:StdGDPR, Section:"Chapter IV — Security", Category:"Breach Notification",
			Title:"Notification of a personal data breach to the supervisory authority",
			Description:"In the event of a personal data breach, notify supervisory authority within 72 hours.",
			Guidance:"AXELUS forensics + alerting enables rapid breach detection and evidence collection for 72h reporting.",
			Severity:SevCritical, Automated:true, WAFFeature:"incident_response",
			WAFConfig:"AlertManager: 72h notification pipeline; forensics: evidence ZIP with SHA-256",
			CrossRefs:[]string{"ISO-A.5.26","NIST-RS.RP-1","NIS2-Art.23"}},
		{ID:"GDPR-Art.35", StandardID:StdGDPR, Section:"Chapter IV — Security", Category:"DPIA",
			Title:"Data protection impact assessment",
			Description:"Where processing is likely to result in a high risk, conduct a DPIA before processing.",
			Guidance:"AXELUS compliance reports provide automated risk scoring for DPIA support.",
			Severity:SevMedium, Automated:false, WAFFeature:"data_protection",
			CrossRefs:[]string{"ISO-A.5.7","NIST-GV.RM-1"}},
	}
	for _, c := range controls { l.Register(c) }
}

// ── HIPAA ─────────────────────────────────────────────────────────────────────
func (l *ControlLibrary) loadHIPAA() {
	controls := []Control{
		{ID:"HIPAA-164.308(a)(1)", StandardID:StdHIPAA, Section:"Administrative Safeguards", Category:"Risk Analysis",
			Title:"Security management process — risk analysis",
			Description:"Conduct an accurate and thorough assessment of the potential risks and vulnerabilities to ePHI.",
			Guidance:"AXELUS compliance assessment provides automated risk scoring and gap analysis for ePHI systems.",
			Severity:SevCritical, Automated:true, WAFFeature:"monitoring",
			CrossRefs:[]string{"NIST-GV.RM-1","ISO-A.5.7","SOC2-CC3.1"}},
		{ID:"HIPAA-164.308(a)(5)", StandardID:StdHIPAA, Section:"Administrative Safeguards", Category:"Security Training",
			Title:"Security awareness and training",
			Description:"Implement a security awareness and training program for all workforce members.",
			Guidance:"AXELUS admin portal provides real-time security metrics for workforce awareness.",
			Severity:SevMedium, Automated:false, WAFFeature:"logging",
			CrossRefs:[]string{"ISO-A.5.1","CIS-17.3"}},
		{ID:"HIPAA-164.308(a)(6)", StandardID:StdHIPAA, Section:"Administrative Safeguards", Category:"Incident Response",
			Title:"Security incident procedures",
			Description:"Implement policies and procedures to address security incidents.",
			Guidance:"AXELUS: automated IR chain with PagerDuty + PCAP forensics + BGP null-routing.",
			Severity:SevCritical, Automated:true, WAFFeature:"incident_response",
			CrossRefs:[]string{"PCI-12.10.1","ISO-A.5.26","NIST-RS.RP-1"}},
		{ID:"HIPAA-164.312(a)(1)", StandardID:StdHIPAA, Section:"Technical Safeguards", Category:"Access Control",
			Title:"Technical access controls for ePHI",
			Description:"Implement technical policies and procedures for electronic information systems to only allow access to authorized users.",
			Guidance:"AXELUS RBAC with tenant isolation and audit trail.",
			Severity:SevCritical, Automated:true, WAFFeature:"access_control",
			CrossRefs:[]string{"PCI-7.2.1","ISO-A.8.3","NIST-PR.AC-3"}},
		{ID:"HIPAA-164.312(b)", StandardID:StdHIPAA, Section:"Technical Safeguards", Category:"Audit Controls",
			Title:"Audit controls — record and examine activity",
			Description:"Implement hardware, software, and procedural mechanisms that record and examine activity in information systems.",
			Guidance:"AXELUS: immutable audit log, 365-day retention, Kafka streaming, SIEM forwarding.",
			Severity:SevCritical, Automated:true, WAFFeature:"logging",
			CrossRefs:[]string{"PCI-10.2.1","ISO-A.8.15","SOC2-CC7.2"}},
		{ID:"HIPAA-164.312(d)", StandardID:StdHIPAA, Section:"Technical Safeguards", Category:"Authentication",
			Title:"Person or entity authentication",
			Description:"Implement procedures to verify that a person seeking access to ePHI is the one claimed.",
			Guidance:"AXELUS: JWT, bcrypt, TOTP MFA, UBA behavioral verification.",
			Severity:SevCritical, Automated:true, WAFFeature:"authentication",
			CrossRefs:[]string{"PCI-8.4.2","ISO-A.8.5","NIST-PR.AC-7"}},
		{ID:"HIPAA-164.312(e)(1)", StandardID:StdHIPAA, Section:"Technical Safeguards", Category:"Transmission Security",
			Title:"Transmission security — protect ePHI in transit",
			Description:"Implement technical security measures to guard against unauthorized access to ePHI transmitted over a network.",
			Guidance:"AXELUS: TLS 1.3 enforced, mTLS inter-service, no plaintext HTTP.",
			Severity:SevCritical, Automated:true, WAFFeature:"encryption",
			CrossRefs:[]string{"PCI-4.2.1","ISO-A.8.24","NIST-PR.DS-2"}},
		{ID:"HIPAA-164.514", StandardID:StdHIPAA, Section:"PHI De-identification", Category:"De-identification",
			Title:"De-identification of protected health information",
			Description:"Health information is de-identified when specific identifiers are removed.",
			Guidance:"AXELUS log masking can strip PHI patterns from WAF logs before SIEM forwarding.",
			Severity:SevHigh, Automated:true, WAFFeature:"data_protection",
			CrossRefs:[]string{"GDPR-Art.5","ISO-A.8.24"}},
	}
	for _, c := range controls { l.Register(c) }
}

// ── CIS Controls v8 ───────────────────────────────────────────────────────────
func (l *ControlLibrary) loadCISv8() {
	controls := []Control{
		{ID:"CIS-1.1", StandardID:StdCISv8, Section:"CIS 1 — Inventory", Category:"Asset Inventory",
			Title:"Establish and maintain detailed enterprise asset inventory",
			Description:"Establish and maintain an accurate, detailed, and up-to-date inventory of all enterprise assets.",
			Guidance:"AXELUS: Kubernetes resource inventory, tenant catalog in admin portal.",
			Severity:SevHigh, Automated:true, WAFFeature:"monitoring",
			CrossRefs:[]string{"NIST-ID.AM-1","ISO-A.5.9"}},
		{ID:"CIS-4.1", StandardID:StdCISv8, Section:"CIS 4 — Secure Config", Category:"Secure Configuration",
			Title:"Establish and maintain secure configuration process",
			Description:"Establish and maintain a secure configuration process for enterprise assets and software.",
			Guidance:"AXELUS: Helm chart with hardened defaults, CIS Kubernetes benchmark applied.",
			Severity:SevHigh, Automated:true, WAFFeature:"patch_management",
			CrossRefs:[]string{"PCI-2.2.1","ISO-A.8.9","NIST-PR.IP-1"}},
		{ID:"CIS-5.1", StandardID:StdCISv8, Section:"CIS 5 — Account Mgmt", Category:"Account Management",
			Title:"Establish and maintain an inventory of accounts",
			Description:"Establish and maintain an inventory of all accounts managed in the enterprise.",
			Guidance:"AXELUS admin portal maintains AdminUser and TenantUser inventories.",
			Severity:SevHigh, Automated:true, WAFFeature:"access_control",
			CrossRefs:[]string{"NIST-PR.AC-1","ISO-A.8.5","PCI-7.2.1"}},
		{ID:"CIS-5.2", StandardID:StdCISv8, Section:"CIS 5 — Account Mgmt", Category:"Account Management",
			Title:"Use unique passwords for all enterprise assets",
			Description:"Use unique passwords and do not allow the use of default passwords.",
			Guidance:"AXELUS: unique bcrypt passwords enforced, API keys are cryptographically random.",
			Severity:SevCritical, Automated:true, WAFFeature:"authentication",
			CrossRefs:[]string{"PCI-8.3.6","ISO-A.8.5","NIST-PR.AC-1"}},
		{ID:"CIS-6.3", StandardID:StdCISv8, Section:"CIS 6 — Access Mgmt", Category:"MFA",
			Title:"Require MFA for externally-exposed applications",
			Description:"Require all externally-exposed enterprise applications to have MFA enabled.",
			Guidance:"AXELUS admin and portal APIs support TOTP MFA. Enable enforcement.",
			Severity:SevCritical, Automated:true, WAFFeature:"authentication",
			CrossRefs:[]string{"PCI-8.4.2","ISO-A.8.5","NIST-PR.AC-7"}},
		{ID:"CIS-7.3", StandardID:StdCISv8, Section:"CIS 7 — Vuln Mgmt", Category:"Vulnerability Management",
			Title:"Perform automated operating system patch management",
			Description:"Perform operating system updates on enterprise assets through automated patch management.",
			Guidance:"AXELUS: automated container rebuilds with updated base images via CI/CD.",
			Severity:SevHigh, Automated:true, WAFFeature:"patch_management",
			CrossRefs:[]string{"ISO-A.8.8","NIST-PR.DS-6","PCI-6.2.4"}},
		{ID:"CIS-7.4", StandardID:StdCISv8, Section:"CIS 7 — Vuln Mgmt", Category:"Vulnerability Scanning",
			Title:"Perform automated application patch management",
			Description:"Perform application updates on enterprise assets through automated patch management.",
			Guidance:"AXELUS: Trivy scanning in GitHub Actions CI/CD pipeline.",
			Severity:SevHigh, Automated:true, WAFFeature:"patch_management",
			CrossRefs:[]string{"ISO-A.8.8","PCI-6.2.4","NIST-PR.DS-6"}},
		{ID:"CIS-9.2", StandardID:StdCISv8, Section:"CIS 9 — Email/Browser", Category:"Web Filtering",
			Title:"Use DNS filtering services on all enterprise assets",
			Description:"Use DNS filtering services to block access to known malicious domains.",
			Guidance:"AXELUS: threat intelligence feeds include domain reputation blocking.",
			Severity:SevMedium, Automated:true, WAFFeature:"vulnerability_scan",
			CrossRefs:[]string{"ISO-A.8.23","NIST-PR.DS-6"}},
		{ID:"CIS-10.1", StandardID:StdCISv8, Section:"CIS 10 — Malware", Category:"Malware Defenses",
			Title:"Deploy and maintain anti-malware software",
			Description:"Deploy and maintain anti-malware software on all enterprise assets.",
			Guidance:"AXELUS ML pipeline + OWASP rules + Zero-Day Shield constitute the WAF-layer anti-malware.",
			Severity:SevHigh, Automated:true, WAFFeature:"vulnerability_scan",
			CrossRefs:[]string{"PCI-5.2.1","ISO-A.8.7","NIST-DE.CM-4"}},
		{ID:"CIS-11.3", StandardID:StdCISv8, Section:"CIS 11 — Data Recovery", Category:"Data Recovery",
			Title:"Protect recovery data",
			Description:"Protect recovery data with equivalent controls as original data.",
			Guidance:"AXELUS forensics evidence packages are sealed (SHA-256), stored separately.",
			Severity:SevMedium, Automated:true, WAFFeature:"forensics",
			CrossRefs:[]string{"NIST-RC.RP-1","ISO-A.5.29"}},
		{ID:"CIS-13.1", StandardID:StdCISv8, Section:"CIS 13 — Network Monitor", Category:"Network Monitoring",
			Title:"Centralize security event alerting",
			Description:"Centralize security event alerting across enterprise assets.",
			Guidance:"AXELUS: Kafka stream → SIEM → Prometheus → AlertManager → PagerDuty/Slack/Teams.",
			Severity:SevHigh, Automated:true, WAFFeature:"monitoring",
			CrossRefs:[]string{"ISO-A.5.23","NIST-DE.CM-3","PCI-10.7.1"}},
		{ID:"CIS-13.4", StandardID:StdCISv8, Section:"CIS 13 — Network Monitor", Category:"Network Segmentation",
			Title:"Perform traffic filtering between network segments",
			Description:"Perform traffic filtering between network segments.",
			Guidance:"AXELUS: Kubernetes NetworkPolicies (9 policies, deny-all baseline) + GeoIP blocking.",
			Severity:SevHigh, Automated:true, WAFFeature:"network_segmentation",
			CrossRefs:[]string{"PCI-1.2.1","ISO-A.8.20","NIST-PR.AC-5"}},
		{ID:"CIS-13.7", StandardID:StdCISv8, Section:"CIS 13 — Network Monitor", Category:"IDS/IPS",
			Title:"Deploy a host-based intrusion detection solution",
			Description:"Deploy a host-based intrusion detection solution on enterprise assets.",
			Guidance:"AXELUS WAF acts as network-layer IDS/IPS. DPI engine inspects all protocols.",
			Severity:SevHigh, Automated:true, WAFFeature:"monitoring",
			CrossRefs:[]string{"PCI-11.5.1","ISO-A.8.16","NIST-DE.CM-4"}},
		{ID:"CIS-13.9", StandardID:StdCISv8, Section:"CIS 13 — Network Monitor", Category:"Port Monitoring",
			Title:"Deploy application layer filtering proxy server",
			Description:"Deploy an application layer filtering proxy server between your users and the Internet.",
			Guidance:"AXELUS Tengine reverse proxy with full L7 inspection.",
			Severity:SevHigh, Automated:true, WAFFeature:"monitoring",
			CrossRefs:[]string{"PCI-10.7.1","ISO-A.8.16"}},
		{ID:"CIS-16.14", StandardID:StdCISv8, Section:"CIS 16 — App Security", Category:"Secure Development",
			Title:"Conduct threat modeling",
			Description:"Conduct threat modeling to identify and address security vulnerabilities in applications.",
			Guidance:"AXELUS compliance reports provide automated threat scoring per control.",
			Severity:SevMedium, Automated:true, WAFFeature:"vulnerability_scan",
			CrossRefs:[]string{"PCI-6.2.4","ISO-A.8.25","NIST-PR.IP-2"}},
		{ID:"CIS-17.1", StandardID:StdCISv8, Section:"CIS 17 — IR Mgmt", Category:"Incident Response",
			Title:"Designate personnel to manage incident handling",
			Description:"Designate one key person and at least one backup person to manage enterprise-wide incident handling.",
			Guidance:"AXELUS: automated IR with PagerDuty escalation chains.",
			Severity:SevHigh, Automated:true, WAFFeature:"incident_response",
			CrossRefs:[]string{"PCI-12.10.1","ISO-A.5.26","NIST-RS.RP-1"}},
	}
	for _, c := range controls { l.Register(c) }
}

// ── NIS2 Directive ────────────────────────────────────────────────────────────
func (l *ControlLibrary) loadNIS2() {
	controls := []Control{
		{ID:"NIS2-Art.21-a", StandardID:StdNIS2, Section:"Art. 21 — Cybersecurity", Category:"Risk Management",
			Title:"Policies on risk analysis and information system security",
			Description:"Essential entities must adopt policies on risk analysis and information system security.",
			Guidance:"AXELUS compliance engine provides automated risk analysis for all 10 major standards.",
			Severity:SevCritical, Automated:true, WAFFeature:"monitoring",
			CrossRefs:[]string{"ISO-A.5.7","NIST-GV.RM-1","GDPR-Art.35"}},
		{ID:"NIS2-Art.21-b", StandardID:StdNIS2, Section:"Art. 21 — Cybersecurity", Category:"Incident Handling",
			Title:"Incident handling — detection, analysis, containment, recovery",
			Description:"Essential entities must have policies for incident detection, analysis, containment and recovery.",
			Guidance:"AXELUS: ML detection → Kafka alert → BGP null-route → PagerDuty → PCAP forensics.",
			Severity:SevCritical, Automated:true, WAFFeature:"incident_response",
			CrossRefs:[]string{"GDPR-Art.33","ISO-A.5.26","NIST-RS.RP-1"}},
		{ID:"NIS2-Art.21-c", StandardID:StdNIS2, Section:"Art. 21 — Cybersecurity", Category:"Business Continuity",
			Title:"Business continuity — backup management, disaster recovery, crisis management",
			Description:"Essential entities must have policies for business continuity including backup management.",
			Guidance:"AXELUS: K8s HPA, PDB, multi-replica Tengine, Redis HA, BGP null-routing.",
			Severity:SevHigh, Automated:true, WAFFeature:"network_segmentation",
			CrossRefs:[]string{"ISO-A.5.29","SOC2-A1.1","NIST-RC.RP-1"}},
		{ID:"NIS2-Art.21-d", StandardID:StdNIS2, Section:"Art. 21 — Cybersecurity", Category:"Supply Chain",
			Title:"Supply chain security including security-related aspects of suppliers",
			Description:"Essential entities must address security of supply chains and supplier relationships.",
			Guidance:"AXELUS: Trivy scanning of all container images, dependency audit, SBOM generation.",
			Severity:SevHigh, Automated:true, WAFFeature:"patch_management",
			CrossRefs:[]string{"ISO-A.8.25","NIST-PR.DS-6","CIS-7.3"}},
		{ID:"NIS2-Art.21-e", StandardID:StdNIS2, Section:"Art. 21 — Cybersecurity", Category:"Secure Development",
			Title:"Security in network and information systems acquisition, development and maintenance",
			Description:"Essential entities must implement security in network and information systems throughout their lifecycle.",
			Guidance:"AXELUS: GitOps, Helm versioning, CI/CD with security gates, semantic versioning.",
			Severity:SevHigh, Automated:true, WAFFeature:"patch_management",
			CrossRefs:[]string{"ISO-A.8.25","PCI-6.2.4","CIS-16.14"}},
		{ID:"NIS2-Art.21-f", StandardID:StdNIS2, Section:"Art. 21 — Cybersecurity", Category:"Vulnerability Management",
			Title:"Policies and procedures to assess effectiveness of cybersecurity risk management",
			Description:"Essential entities must assess the effectiveness of cybersecurity risk management measures.",
			Guidance:"AXELUS compliance monitor runs quarterly assessments and detects drift (>5pt drop triggers alert).",
			Severity:SevHigh, Automated:true, WAFFeature:"monitoring",
			CrossRefs:[]string{"SOC2-CC7.1","ISO-A.8.16","NIST-DE.CM-7"}},
		{ID:"NIS2-Art.21-g", StandardID:StdNIS2, Section:"Art. 21 — Cybersecurity", Category:"Cryptography",
			Title:"Use of cryptography and encryption",
			Description:"Essential entities must use cryptography and encryption including end-to-end encryption where appropriate.",
			Guidance:"AXELUS: TLS 1.3, AES-256-GCM, ED25519 signing, bcrypt authentication.",
			Severity:SevCritical, Automated:true, WAFFeature:"encryption",
			CrossRefs:[]string{"ISO-A.8.24","PCI-4.2.1","HIPAA-164.312(e)(1)","GDPR-Art.32"}},
		{ID:"NIS2-Art.21-h", StandardID:StdNIS2, Section:"Art. 21 — Cybersecurity", Category:"Access Control",
			Title:"Human resources security, access control policies and asset management",
			Description:"Essential entities must implement access control and asset management policies.",
			Guidance:"AXELUS RBAC system (8 roles, 14 permissions) + tenant isolation.",
			Severity:SevHigh, Automated:true, WAFFeature:"access_control",
			CrossRefs:[]string{"PCI-7.2.1","ISO-A.8.3","CIS-5.1"}},
		{ID:"NIS2-Art.21-i", StandardID:StdNIS2, Section:"Art. 21 — Cybersecurity", Category:"MFA",
			Title:"Use of multi-factor authentication and continuous authentication",
			Description:"Essential entities must use multi-factor authentication or continuous authentication solutions.",
			Guidance:"AXELUS: TOTP MFA + UBA continuous authentication (behavioral analytics).",
			Severity:SevCritical, Automated:true, WAFFeature:"authentication",
			CrossRefs:[]string{"PCI-8.4.2","ISO-A.8.5","CIS-6.3"}},
		{ID:"NIS2-Art.23", StandardID:StdNIS2, Section:"Art. 23 — Reporting", Category:"Incident Reporting",
			Title:"Reporting obligations for significant incidents — 24h/72h thresholds",
			Description:"Essential entities must report significant incidents within 24h (early warning) and 72h (formal report).",
			Guidance:"AXELUS: automated alerting within seconds of detection. Forensics evidence for 72h formal report.",
			Severity:SevCritical, Automated:true, WAFFeature:"incident_response",
			WAFConfig:"PagerDuty: P1 alert in <60s. Forensics ZIP available for authority submission.",
			CrossRefs:[]string{"GDPR-Art.33","ISO-A.5.26","NIST-RS.RP-1"}},
	}
	for _, c := range controls { l.Register(c) }
}

// ── OWASP Top 10 (2021) ───────────────────────────────────────────────────────
func (l *ControlLibrary) loadOWASP() {
	controls := []Control{
		{ID:"OWASP-A01", StandardID:StdOWASP, Section:"A01:2021", Category:"Broken Access Control",
			Title:"Broken Access Control — prevent unauthorized access",
			Description:"Access control enforces policy so users cannot act outside their intended permissions.",
			Guidance:"AXELUS: RBAC, tenant isolation, NetworkPolicies, audit log of all access.",
			Severity:SevCritical, Automated:true, WAFFeature:"access_control",
			CrossRefs:[]string{"PCI-7.2.1","ISO-A.8.3","CIS-6.1"}},
		{ID:"OWASP-A02", StandardID:StdOWASP, Section:"A02:2021", Category:"Cryptographic Failures",
			Title:"Cryptographic Failures — protect data with strong cryptography",
			Description:"Data that requires protection (passwords, card numbers, health records) must be encrypted.",
			Guidance:"AXELUS: TLS 1.3, AES-256-GCM, ED25519, bcrypt cost=12, no weak ciphers.",
			Severity:SevCritical, Automated:true, WAFFeature:"encryption",
			CrossRefs:[]string{"PCI-4.2.1","ISO-A.8.24","NIST-PR.DS-2"}},
		{ID:"OWASP-A03", StandardID:StdOWASP, Section:"A03:2021", Category:"Injection",
			Title:"Injection — prevent SQL/NoSQL/Command injection",
			Description:"Injection flaws occur when untrusted data is sent to an interpreter as part of a command or query.",
			Guidance:"AXELUS: ML pipeline (SQLi class, score 0-1), OWASP rules, DPI body inspection.",
			Severity:SevCritical, Automated:true, WAFFeature:"vulnerability_scan",
			WAFConfig:"ML OutputClasses: sql_injection, nosql_injection, command_injection — all active",
			CrossRefs:[]string{"PCI-6.4.1","ISO-A.8.8","NIST-DE.CM-4"}},
		{ID:"OWASP-A04", StandardID:StdOWASP, Section:"A04:2021", Category:"Insecure Design",
			Title:"Insecure Design — threat modeling and secure design patterns",
			Description:"Insecure design is a broad category for missing or ineffective control design.",
			Guidance:"AXELUS compliance reports provide control gap analysis and remediation steps.",
			Severity:SevHigh, Automated:false, WAFFeature:"vulnerability_scan",
			CrossRefs:[]string{"ISO-A.8.25","PCI-6.2.4","NIST-PR.IP-2"}},
		{ID:"OWASP-A05", StandardID:StdOWASP, Section:"A05:2021", Category:"Security Misconfiguration",
			Title:"Security Misconfiguration — default configs, error messages, unpatched",
			Description:"Misconfiguration is the most commonly seen issue, including default credentials.",
			Guidance:"AXELUS: Helm hardened defaults, ensureSuperAdmin() forces password change, Trivy scanning.",
			Severity:SevHigh, Automated:true, WAFFeature:"patch_management",
			CrossRefs:[]string{"PCI-2.2.1","CIS-4.1","NIST-PR.IP-1"}},
		{ID:"OWASP-A06", StandardID:StdOWASP, Section:"A06:2021", Category:"Vulnerable Components",
			Title:"Vulnerable and Outdated Components",
			Description:"Components such as libraries, frameworks, and other software modules used with known vulnerabilities.",
			Guidance:"AXELUS: Trivy scans all container images in CI. Go module audit. Automated dependency updates.",
			Severity:SevHigh, Automated:true, WAFFeature:"patch_management",
			CrossRefs:[]string{"PCI-6.4.1","CIS-7.3","NIST-PR.DS-6"}},
		{ID:"OWASP-A07", StandardID:StdOWASP, Section:"A07:2021", Category:"Authentication Failures",
			Title:"Identification and Authentication Failures",
			Description:"Incorrect implementation of authentication allows attackers to compromise passwords, keys, or session tokens.",
			Guidance:"AXELUS: bcrypt (cost=12), JWT 8h expiry, TOTP MFA, UBA credential stuffing detection.",
			Severity:SevCritical, Automated:true, WAFFeature:"authentication",
			CrossRefs:[]string{"PCI-8.3.6","PCI-8.4.2","ISO-A.8.5","CIS-6.3"}},
		{ID:"OWASP-A08", StandardID:StdOWASP, Section:"A08:2021", Category:"Software Integrity",
			Title:"Software and Data Integrity Failures",
			Description:"Software and data integrity failures relating to code and infrastructure that does not protect against integrity violations.",
			Guidance:"AXELUS: Git commit signing, container image signing (Trivy), Helm chart checksums.",
			Severity:SevHigh, Automated:true, WAFFeature:"patch_management",
			CrossRefs:[]string{"NIST-PR.DS-6","CIS-7.3","ISO-A.8.25"}},
		{ID:"OWASP-A09", StandardID:StdOWASP, Section:"A09:2021", Category:"Logging & Monitoring",
			Title:"Security Logging and Monitoring Failures",
			Description:"Without logging and monitoring, breaches cannot be detected. Logs must be protected against tampering.",
			Guidance:"AXELUS: immutable audit log, Kafka stream, SIEM forwarding, Prometheus alerting.",
			Severity:SevHigh, Automated:true, WAFFeature:"logging",
			CrossRefs:[]string{"PCI-10.2.1","ISO-A.8.15","NIST-PR.PT-1"}},
		{ID:"OWASP-A10", StandardID:StdOWASP, Section:"A10:2021", Category:"SSRF",
			Title:"Server-Side Request Forgery (SSRF)",
			Description:"SSRF flaws occur whenever a web application is fetching a remote resource without validating the user-supplied URL.",
			Guidance:"AXELUS: ML OutputClass ssrf, SSRF pattern detection in headers (169.254.169.254), DPI.",
			Severity:SevHigh, Automated:true, WAFFeature:"vulnerability_scan",
			WAFConfig:"ML: ssrf class active. Header inspection: block 169.254.169.254, ::1, localhost targets",
			CrossRefs:[]string{"PCI-6.4.1","ISO-A.8.8","NIST-DE.CM-4"}},
	}
	for _, c := range controls { l.Register(c) }
}

// ── FedRAMP High ──────────────────────────────────────────────────────────────
func (l *ControlLibrary) loadFedRAMP() {
	controls := []Control{
		{ID:"FEDRAMP-AC-2", StandardID:StdFedRAMP, Section:"AC — Access Control", Category:"Account Management",
			Title:"Account management",
			Description:"Manage information system accounts, including establishing, activating, modifying, reviewing, and disabling accounts.",
			Guidance:"AXELUS admin portal: full CRUD for AdminUser and TenantUser with audit trail.",
			Severity:SevCritical, Automated:true, WAFFeature:"access_control",
			CrossRefs:[]string{"PCI-7.2.1","ISO-A.8.3","CIS-5.1","NIST-PR.AC-1"}},
		{ID:"FEDRAMP-AC-17", StandardID:StdFedRAMP, Section:"AC — Access Control", Category:"Remote Access",
			Title:"Remote access — secure all remote connections",
			Description:"Establish and document usage restrictions and implementation guidance for each type of remote access.",
			Guidance:"AXELUS: TLS 1.3 + mTLS for all remote admin connections. JWT with short expiry.",
			Severity:SevCritical, Automated:true, WAFFeature:"encryption",
			CrossRefs:[]string{"PCI-2.2.7","ISO-A.8.24","NIST-PR.DS-2"}},
		{ID:"FEDRAMP-AU-2", StandardID:StdFedRAMP, Section:"AU — Audit", Category:"Audit Events",
			Title:"Audit events — define what is auditable",
			Description:"Determine events that the information system is capable of auditing.",
			Guidance:"AXELUS: all events audited — login, admin actions, config changes, alerts, forensics.",
			Severity:SevHigh, Automated:true, WAFFeature:"logging",
			CrossRefs:[]string{"PCI-10.2.1","ISO-A.8.15","HIPAA-164.312(b)"}},
		{ID:"FEDRAMP-AU-9", StandardID:StdFedRAMP, Section:"AU — Audit", Category:"Audit Protection",
			Title:"Protection of audit information",
			Description:"The information system protects audit information and tools from unauthorized access, modification, and deletion.",
			Guidance:"AXELUS: audit records stored in append-only Kafka topic (RF=3) + PostgreSQL with no-delete policy.",
			Severity:SevCritical, Automated:true, WAFFeature:"logging",
			CrossRefs:[]string{"ISO-A.8.15","SOC2-CC7.2","NIST-PR.PT-1"}},
		{ID:"FEDRAMP-CM-6", StandardID:StdFedRAMP, Section:"CM — Config Mgmt", Category:"Configuration Settings",
			Title:"Configuration settings — establish and document baseline",
			Description:"Establish and document configuration settings for all IT products employed within the information system.",
			Guidance:"AXELUS: all config in Helm values.yaml + Kubernetes manifests. GitOps-enforced.",
			Severity:SevHigh, Automated:true, WAFFeature:"patch_management",
			CrossRefs:[]string{"PCI-2.2.1","ISO-A.8.9","CIS-4.1"}},
		{ID:"FEDRAMP-IA-2", StandardID:StdFedRAMP, Section:"IA — Identification", Category:"MFA",
			Title:"Identification and authentication (organizational users) — MFA required",
			Description:"The information system uniquely identifies and authenticates organizational users and implements MFA for network access to privileged accounts.",
			Guidance:"AXELUS: TOTP MFA for all admin accounts. Enforce mfa_required=true.",
			Severity:SevCritical, Automated:true, WAFFeature:"authentication",
			CrossRefs:[]string{"PCI-8.4.2","ISO-A.8.5","NIS2-Art.21-i","CIS-6.3"}},
		{ID:"FEDRAMP-IR-4", StandardID:StdFedRAMP, Section:"IR — Incident Response", Category:"Incident Handling",
			Title:"Incident handling — automated response capabilities",
			Description:"Implement an incident handling capability including automated mechanisms to support incident handling.",
			Guidance:"AXELUS: automated IR — detect (ML) → isolate (BGP null-route) → capture (PCAP) → alert → recover.",
			Severity:SevCritical, Automated:true, WAFFeature:"incident_response",
			CrossRefs:[]string{"PCI-12.10.1","ISO-A.5.26","NIST-RS.RP-1","NIS2-Art.21-b"}},
		{ID:"FEDRAMP-RA-5", StandardID:StdFedRAMP, Section:"RA — Risk Assessment", Category:"Vulnerability Scanning",
			Title:"Vulnerability scanning — organizational information systems",
			Description:"Scan for vulnerabilities in the information system and applications at least monthly.",
			Guidance:"AXELUS: continuous WAF-level vulnerability scanning + quarterly compliance reports.",
			Severity:SevHigh, Automated:true, WAFFeature:"vulnerability_scan",
			CrossRefs:[]string{"PCI-11.3.1","ISO-A.8.8","CIS-7.4","NIST-DE.CM-8"}},
		{ID:"FEDRAMP-SC-7", StandardID:StdFedRAMP, Section:"SC — System Protection", Category:"Boundary Protection",
			Title:"Boundary protection — monitor and control communications at the boundary",
			Description:"The information system monitors and controls communications at the external boundary and key internal boundaries.",
			Guidance:"AXELUS: GeoIP + DPI + DDoS mitigation + BGP null-routing at all network boundaries.",
			Severity:SevCritical, Automated:true, WAFFeature:"network_segmentation",
			CrossRefs:[]string{"PCI-1.2.1","ISO-A.8.20","NIST-PR.AC-5","NIS2-Art.21-g"}},
		{ID:"FEDRAMP-SI-3", StandardID:StdFedRAMP, Section:"SI — System Integrity", Category:"Malware Protection",
			Title:"Malicious code protection — employ malicious code protection mechanisms",
			Description:"Employ malicious code protection mechanisms at information system entry and exit points.",
			Guidance:"AXELUS ML Zero-Day Shield + OWASP rules + WebSocket/gRPC DPI = full coverage.",
			Severity:SevCritical, Automated:true, WAFFeature:"vulnerability_scan",
			CrossRefs:[]string{"PCI-5.2.1","ISO-A.8.7","CIS-10.1","NIST-DE.CM-4"}},
	}
	for _, c := range controls { l.Register(c) }
}
