apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: ironwall-prometheus
    access: proxy
    url: http://ironwall-prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: POST

  - name: PostgreSQL
    type: postgres
    uid: ironwall-postgres
    url: ironwall-postgres:5432
    database: ironwall
    user: ironwall
    editable: false
    secureJsonData:
      password: "${POSTGRES_PASSWORD}"
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      postgresVersion: 1500
      timescaledb: false

  - name: Loki
    type: loki
    uid: ironwall-loki
    access: proxy
    url: http://ironwall-loki:3100
    editable: false
    jsonData:
      maxLines: 1000
